// Change these to rebrand the app's in-app text. The logo image lives at
// src/assets/logo.png — replace that file (keep the filename) to change the
// mark shown on the login screen and menu header.
//
// The app's NAME as installed on the phone (shown under the home-screen icon)
// and its actual app icon are separate — those live in the native project
// generated by APK_BUILD_GUIDE.md (app.json's "displayName", and
// android/app/src/main/res/mipmap-*/ic_launcher.png). See BRANDING_GUIDE.md
// at the project root for the full checklist.
export const APP_NAME = "Godelicious";
export const APP_TAGLINE = "Catering, delivered.";
